Listen = ":8080"
PluginDir = "plugins"
PluginTempDir = "tmp"

[Pages]
  "401" = "/pages/login.html"

[Users]
  admin = "$2a$10$MnmhGyn4pELBONBmkY.XDOcEXDUJjMYPtVnFrdTQLeJYPZCLEJFeS" # password: admin

[Plugins]
  [Plugins.default]
    Restart = "no"
    RunAsUser = ""

  # Coreplugins
  [Plugins.hello]
    Restart = "always"
    [Plugins.hello.Params]
      greeting = "env://HIHI"
  [Plugins.web-assets]
    Restart = "always"
  [Plugins.login]
    Restart = "always"
  [Plugins.navigator]
    Restart = "always"
  [Plugins.plugin-manager]
    Restart = "always"
