Listen = ":8080"
ServiceDir = "services"
ServiceTempDir = "tmp"

[Pages]
  "401" = "/pages/login.html"

[Users]
  admin = "$2a$10$MnmhGyn4pELBONBmkY.XDOcEXDUJjMYPtVnFrdTQLeJYPZCLEJFeS" # password: admin

[Services]
  [Services.default]
    Restart = "no"
    RunAsUser = ""

  # Core services
  [Services.hello]
    Restart = "always"
    [Services.hello.Params]
      greeting = "env://HIHI"
  [Services.web-assets]
    Restart = "always"
  [Services.login]
    Restart = "always"
  [Services.navigator]
    Restart = "always"
  [Services.service-manager]
    Restart = "always"
